[project]
name = "joker-reviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.19",
    "langchain-openai>=0.3.7",
    "langgraph>=0.3.2",
]
